# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip &&
        pip install -r ./requirements.txt &&
        pip install build
    - name: Build package
      run: python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
  
  release:
    name: Upload Release Asset
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist

    - name: Upload release assets
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "dist/*"
        update_latest_release: true
        release_id: ${{ github.event.release.id }}
